version: '3.6'

services:
  ci-build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ModernUIApp/ModernUIApp.csproj && dotnet restore ./ModernUIApp.Tests/ModernUIApp.Tests.csproj && dotnet publish ./ModernUIApp/ModernUIApp.csproj -c Release -o ./obj/Docker/publish"