version: '3.6'

services:
  ci-build:
    image: microsoft/dotnet:2.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./ModernApiApp/ModernApiApp.csproj && dotnet restore ./ModernApiApp.Tests/ModernApiApp.Tests.csproj && dotnet publish ./ModernApiApp/ModernApiApp.csproj -c Release -o ./obj/Docker/publish"